In [3]:
import numpy as np

In [17]:
a =  np.arange(1, 25)

In [23]:
b = a.reshape(6, 4)

In [25]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [27]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [35]:
a[3] = 5

In [37]:
a

array([ 1,  2,  3,  5,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [41]:
a[::-1][1]

23

In [44]:
b

array([[ 1,  2,  3,  5],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [50]:
b[2:5, 2:4]

array([[11, 12],
       [15, 16],
       [19, 20]])

In [67]:
c = np.arange(100).reshape(10, 10)
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [91]:
c[[1, 5], 1]

array([11, 51])

In [75]:
c[1, 1]

11

In [81]:
c[[0, 8],[5, 8]]

array([ 5, 88])

In [85]:
arr3 = np.random.randint(1, 50, size=(3, 4))
arr3

array([[ 6, 30, 18, 10],
       [22,  6, 38, 47],
       [25,  5,  8, 12]])

In [87]:
arr3 < 10

array([[ True, False, False, False],
       [False,  True, False, False],
       [False,  True,  True, False]])

In [89]:
arr3[arr3 < 10]

array([6, 6, 5, 8])

In [96]:
d = np.arange(100).reshape(10, 10)

In [98]:
d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [100]:
d + 10

array([[ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109]])

In [105]:
d ** d

array([[          1,           1,           4,          27,         256,
               3125,       46656,      823543,    16777216,   387420489],
       [ 1410065408,  1843829075,  -251658240, -1692154371, -1282129920,
         1500973039,           0,  1681328401,   457441280,  -306639989],
       [          0,   878082373,   977272832, -1276351769,           0,
         1296002393,   603979776,  -714244925,           0, -1266004979],
       [ 1073741824, -2010103841,           0,   942687265,           0,
          618402555,           0,  -200711083,           0,  1583713495],
       [          0,  2110296937,           0,   407106611,           0,
        -1714755555,           0,  1686099919,           0,    20963633],
       [          0,  -329759125,           0, -1690305179,           0,
         2006722247,           0,  1071068025,           0,   915746723],
       [          0,  1062783533,           0,  1526857663,           0,
         1526861889,           0,   882693595

In [112]:
a = np.arange(1, 10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
np.add(a, 2)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [124]:
np.subtract(a, 2)

array([-1,  0,  1,  2,  3,  4,  5,  6,  7])

In [128]:
a = np.array([1, 1, 2, 2, 3, 3, 3])
a

array([1, 1, 2, 2, 3, 3, 3])

In [141]:
np.mean(a)

2.142857142857143

In [143]:
np.mode(a)

AttributeError: module 'numpy' has no attribute 'mode'

In [145]:
np.std(a)

0.8329931278350429

In [147]:
np.median(a)

2.0

In [150]:
np.ptp(a)

2